name: Validate Terraform

on: [push]

jobs:
  tf_fmt:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.1.3
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: 'terraform/unittests'

    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7

    - name: Terraform Plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.1.3
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: 'terraform/unittests'
